
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function isSupabasePoolerUrl(value: string) {
  try {
    return new URL(value).hostname.endsWith(".pooler.supabase.com");
  } catch {
    return false;
  }
}


function getSupabaseProjectRef(candidate: URL) {
  const supabaseProjectUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (supabaseProjectUrl) {
    try {
      return new URL(supabaseProjectUrl).hostname.split(".")[0] ?? null;
    } catch {
      // Fall through to deriving from the username.
    }
  }

  const usernameParts = decodeURIComponent(candidate.username).split(".");
  return usernameParts.length > 1 ? usernameParts.slice(1).join(".") : null;
}

function deriveSupabaseDirectUrl(value?: string) {
  if (!value) return null;

  let candidate: URL;

  try {
    candidate = new URL(value);
  } catch {
    return null;
  }

  if (!candidate.hostname.endsWith(".pooler.supabase.com")) {
    return candidate.toString();
  }

  const projectRef = getSupabaseProjectRef(candidate);
  const usernameParts = decodeURIComponent(candidate.username).split(".");
  const databaseUser = usernameParts[0];

  if (!projectRef || !databaseUser) return null;

  candidate.hostname = `db.${projectRef}.supabase.co`;
  candidate.port = "5432";
  candidate.username = databaseUser;
  candidate.searchParams.delete("connection_limit");
  candidate.searchParams.delete("pgbouncer");

  if (!candidate.searchParams.has("sslmode")) {
    candidate.searchParams.set("sslmode", "require");
  }

  return candidate.toString();
}

function resolveDirectUrl() {
  const explicitDirectUrl = process.env.DIRECT_URL?.trim();
  const databaseUrl = process.env.DATABASE_URL?.trim();

  // An explicit DIRECT_URL always wins — it is the recommended Supabase setup.
  if (explicitDirectUrl) {
    return explicitDirectUrl;
  }

  if (!databaseUrl) {
    return "";
  }

  // If DATABASE_URL is not a Supabase pooler URL at all, use it directly.
  if (!isSupabasePoolerUrl(databaseUrl)) {
    return databaseUrl;
  }

  // DATABASE_URL points to a Supabase pooler (either session :5432 or
  // transaction :6543). Prisma's schema engine opens many connections for
  // migrations and will immediately exceed the pooler's connection cap
  // (EMAXCONNSESSION). Derive the direct db.*.supabase.co host instead so
  // that `prisma migrate deploy` bypasses the pooler entirely.
  return (
    deriveSupabaseDirectUrl(databaseUrl) ??
    databaseUrl
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fall back to empty string so `prisma generate` (schema-only) works
    // even when DATABASE_URL is not yet available (e.g. during Vercel install).
    url: process.env.DATABASE_URL ?? "",
    directUrl: resolveDirectUrl(),
  },
});
