
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function isSupabasePoolerUrl(value: string) {
  try {
    return new URL(value).hostname.endsWith(".pooler.supabase.com");
  } catch {
    return false;
  }
}

function isSupabaseTransactionPoolerUrl(value: string) {
  try {
    const candidate = new URL(value);
    return (
      candidate.hostname.endsWith(".pooler.supabase.com") &&
      candidate.port === "6543"
    );
  } catch {
    return false;
  }
}

function getSupabaseProjectRef(candidate: URL) {
  const supabaseProjectUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;

  if (supabaseProjectUrl) {
    try {
      return new URL(supabaseProjectUrl).hostname.split(".")[0] ?? null;
    } catch {
      // Fall through to deriving from the username.
    }
  }

  const usernameParts = decodeURIComponent(candidate.username).split(".");
  return usernameParts.length > 1 ? usernameParts.slice(1).join(".") : null;
}

function deriveSupabaseDirectUrl(value?: string) {
  if (!value) return null;

  let candidate: URL;

  try {
    candidate = new URL(value);
  } catch {
    return null;
  }

  if (!candidate.hostname.endsWith(".pooler.supabase.com")) {
    return candidate.toString();
  }

  const projectRef = getSupabaseProjectRef(candidate);
  const usernameParts = decodeURIComponent(candidate.username).split(".");
  const databaseUser = usernameParts[0];

  if (!projectRef || !databaseUser) return null;

  candidate.hostname = `db.${projectRef}.supabase.co`;
  candidate.port = "5432";
  candidate.username = databaseUser;
  candidate.searchParams.delete("connection_limit");
  candidate.searchParams.delete("pgbouncer");

  if (!candidate.searchParams.has("sslmode")) {
    candidate.searchParams.set("sslmode", "require");
  }

  return candidate.toString();
}

function resolveDirectUrl() {
  const explicitDirectUrl = process.env.DIRECT_URL?.trim();
  const databaseUrl = process.env.DATABASE_URL?.trim();

  if (!databaseUrl) {
    return explicitDirectUrl ?? "";
  }

  // Non-Supabase databases can continue using an explicit direct URL override.
  if (!isSupabasePoolerUrl(databaseUrl)) {
    return explicitDirectUrl || databaseUrl;
  }

  // Supabase session pooler URLs on :5432 are the supported migration target
  // for server-based deploy environments like Vercel builds. Rewriting them to
  // db.*.supabase.co can fail when that direct host is IPv6-only or otherwise
  // unavailable in the build network.
  if (!isSupabaseTransactionPoolerUrl(databaseUrl)) {
    return databaseUrl;
  }

  // When the app runtime uses Supabase's transaction pooler on :6543, Prisma
  // migrations need a non-pooled target. Prefer an explicit DIRECT_URL and
  // otherwise derive the direct host from the pooler connection string.
  return (
    explicitDirectUrl ??
    deriveSupabaseDirectUrl(databaseUrl) ??
    databaseUrl
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fall back to empty string so `prisma generate` (schema-only) works
    // even when DATABASE_URL is not yet available (e.g. during Vercel install).
    url: process.env.DATABASE_URL ?? "",
    directUrl: resolveDirectUrl(),
  },
});
